### ISSUE TITLE
Kobo Libra 2 - button support

### ISSUE THREAD

**Issue by tadassce** [usetrmnl/trmnl-kobo#9]
Firstly, thanks so much for all this amazing work and sharing it. The instructions were clear and I was able to set up TRMNL on my Kobo Libra 2 without any issues. ❤️

The only tweak I needed to do is set `ConnectedGracePeriod` to `15` in `config.json`.

So I think you can add a mention that it works on this device too. Let me know if you need help testing some edge cases.

It would be amazing if I could also use the next/prev page buttons to move between plugins in the playlist.

Please let me know how can I help test or maybe even implement this. Thank you 🙏

**Comment by rlesavre** [comment]
There is only a next screen possible i think with the TRMNL APIs, i might be wrong, any way, a touch/slide on the screen should wake up the Kobo, and perform a change screen. Does that works ?

I'll update the wiki to reflect your success and recommendations.

Thanks for the feedback

**Comment by tadassce** [comment]
Oh I hadn't realized that before, thanks. So yes, a swipe or tap on the screen does indeed wake up the Kobo and performs a change, it works, it just takes around 30 seconds from the tap to the moment the screen changes :) Maybe that's expected since it need to reconnect to the wifi, download the next image (if I understand it well)… So yeah, with that, honestly the buttons don't matter - this is definitely good enough, feel free to close this issue. Thanks!

**Comment by rlesavre** [comment]
Perfect! Would you mind sending a photo of your Kobo with a TRMNL dashboard on it to update the readme ?

Thanks

**Comment by tadassce** [comment]
Sure, here you go:

![Image](https://github.com/user-attachments/assets/95e2d485-a71a-4848-8d51-2cd5c09dda8f)

**Comment by rlesavre** [comment]
Note, would like to have a settings to invert the display, so that the Kobo is note upside down ?

**Comment by rlesavre** [comment]
Add an option to flip the screen orentation in the config settings

**Comment by lzilioli** [comment]
Some rotation options would help the Clara 2e as well. When I use the terminal OG device mode, the images are rendering in portrait and I need to rotate it to landscape (paper white resolution is weird and plugins have a weird layout so I want to use terminal og option with the clara)

**Comment by ronakjain90** [comment]
I'm from the TRMNL team, I just fixed screen rotation issue generated for Kobo Libra 2. You shouldn't have to use TRMNL OG as your device model on your Kobo device. You can try Kobo Libra 2 and if that orientation works, start a support chat and we can properly configure device model that doesn't  properly work as well.

**Comment by ctlw83** [comment]
I noticed the same thing with the Kobo Libra H20.  (I have the config set to Kobo Libra 2 as it is the same resolution)

I also had noticed the change in orientation over the past couple of days, but it isn't for all plugins/recipes, only about half.

I just rebooted the device since you made the changes and did a manual refresh of my plugins.  I'm still experiencing the issue.  Any ideas?

**Comment by ronakjain90** [comment]
> but it isn't for all plugins/recipes, only about half.

Unfortunately the recipe author has to make changes to the recipe to make full use of available device resolution. You can try the screenshot or a picture plugin to see if it occupies full screen now.

**Comment by ctlw83** [comment]
Update - Since the change ALL plugins and recipes render vertically instead of horizontally.

I'm using a Kobo Libra H20 with the Kobo Libra 2 setting in the TRMNL dashboard
My JSON Config has these settings
{
    "TrmnlId": "CENSORED",
    "TrmnlToken": "CENSORED",
    "TrmnlApiUrl": "https://usetrmnl.com/api",
    "IgnoreCurlErrors": true,
    "DebugToScreen": 0,
    "LoopMaxIteration": 0,
    "ConnectedGracePeriod": 15,
    "ImageFormat": "png" 
}
